# Generated by Django 3.1.7 on 2021-08-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_requestblood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestblood',
            name='district',
        ),
        migrations.RemoveField(
            model_name='requestblood',
            name='donation_location',
        ),
        migrations.AddField(
            model_name='requestblood',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='requestblood',
            name='city',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='requestblood',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
