# Generated by Django 3.1.7 on 2021-08-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='address',
            field=models.TextField(default='', max_length=500),
        ),
    ]
